from __future__ import annotations

from pathlib import Path

# Backgrounds
BG_DARKEST = "#08080C"
BG_PRIMARY = "#0E0F14"
BG_SURFACE = "#151620"
BG_ELEVATED = "#1C1D2A"

# Borders
BORDER_SUBTLE = "#1E1F2E"
BORDER = "#2A2B3D"

# Text
TEXT_PRIMARY = "#E8EAED"
TEXT_SECONDARY = "#7C7E8C"
TEXT_DISABLED = "#3E3F4D"

# Accent
ACCENT = "#6366F1"
ACCENT_LIGHT = "#818CF8"
ACCENT_GRADIENT_END = "#A855F7"

# Semantic
SUCCESS = "#22C55E"
DANGER = "#EF4444"
DANGER_HOVER = "#DC2626"
WARNING = "#F59E0B"

# Glow
GLOW_COLOUR = ACCENT
GLOW_OPACITY = 0.07
GLOW_RADIUS_FACTOR = 0.7
GLOW_ORIGIN_X = 1.0  # 0.0 = left, 1.0 = right
GLOW_ORIGIN_Y = 1.0  # 0.0 = top, 1.0 = bottom

# Dialogue
DIALOGUE_WIDTH = 340
DIALOGUE_ICON_WIDTH = 32
DIALOGUE_ICON_FONT_SIZE = 24
DIALOGUE_TITLE_FONT_SIZE = 14
DIALOGUE_CONTENT_FONT_SIZE = 12
DIALOGUE_BTN_WIDTH = 72
DIALOGUE_BORDER_RADIUS = 10
DIALOGUE_BTN_BORDER_RADIUS = 6
DIALOGUE_PADDING = 16
DIALOGUE_TEXT_SPACING = 4
DIALOGUE_SHADOW_BLUR = 24
DIALOGUE_SHADOW_OFFSET = 6

# Resources
_RESOURCES_DIR = Path(__file__).resolve().parent.parent / "resources"
LOGO_SMALL = str(_RESOURCES_DIR / "pymymc_logo_small.png")
LOGO_ICON = str(_RESOURCES_DIR / "pymymc_ico.ico")
